# src/utils/google_forms/evaluate_round.py

import json
import os
from typing import Dict, Tuple, List, Any

from src.utils.google_forms.form_api import get_forms_service
from src.utils.google_forms.save_results_to_sheet import save_round_result



# =========================================================
# Helpers
# =========================================================

def clean(text):
    if text is None:
        return ""
    return " ".join(str(text).split()).strip()


# =========================================================
# GOOGLE FORM HELPERS (L1 / L2 / L3 / L5)
# =========================================================

def fetch_latest_answers(form_id: str) -> Dict[str, str]:
    """
    Returns: {questionId: user_answer_text} for the latest submission.
    """
    forms = get_forms_service()

    resp = forms.forms().responses().list(formId=form_id).execute()
    responses = resp.get("responses", [])
    if not responses:
        return {}

    responses.sort(
        key=lambda r: r.get("lastSubmittedTime", r.get("createTime", "")),
    )
    latest = responses[-1]

    answers_map = {}
    for qid, ans in latest.get("answers", {}).items():
        text_answers = ans.get("textAnswers", {}).get("answers", [])
        if text_answers:
            answers_map[qid] = clean(text_answers[0].get("value", ""))

    return answers_map


def check_if_response_exists(form_id: str) -> bool:
    """
    Used by Streamlit timer logic.
    """
    forms = get_forms_service()
    resp = forms.forms().responses().list(formId=form_id, pageSize=1).execute()
    return bool(resp.get("responses"))


def build_question_index(candidate_data: dict) -> Dict[str, Tuple[str, str]]:
    """
    Build map: question_title_clean -> (correct_answer, level)
    Skip candidate + L4.
    """
    index: Dict[str, Tuple[str, str]] = {}

    for level, questions in candidate_data.items():
        if level in ("candidate", "L4"):
            continue
        if not isinstance(questions, list):
            continue

        for q in questions:
            title = clean(q.get("question"))
            correct = q.get("correct_answer")
            if title and correct is not None:
                index[title] = (str(correct).strip(), level)

    return index


# =========================================================
# L4 EVALUATION (CODING ROUND)
# =========================================================

def evaluate_l4_round(uid: str) -> Dict[str, Any]:
    """
    Evaluate L4 coding round from JSON generated by exam_server.py
    """
    path = f"question_bank/l4_results/{uid}.json"

    if not os.path.exists(path):
        return {
            "uid": uid,
            "round_name": "L4",
            "status": "NO_RESPONSES",
            "total_questions": 0,
            "correct_count": 0,
            "score_percent": 0.0,
            "spreadsheet_id": None,
            "details": [],
        }

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    total = data.get("total_tests", 0)
    passed = data.get("passed_tests", 0)
    score_percent = data.get("score_percent", 0)
    focus_lost = data.get("focus_lost", 0)

    # STRICT RULE
    status = "PASS" if score_percent >= 75 and focus_lost == 0 else "FAIL"

    spreadsheet_id = save_round_result(
        uid=uid,
        candidate_name="",
        email="",
        round_name="L4",
        total_questions=total,
        correct_answers=passed,
        score_percent=score_percent,
        status=status,
    )

    return {
        "uid": uid,
        "round_name": "L4",
        "total_questions": total,
        "correct_count": passed,
        "score_percent": score_percent,
        "focus_lost": focus_lost,
        "status": status,
        "spreadsheet_id": spreadsheet_id,
        "details": [
            {
                "title": "Coding Test",
                "user_answer": f"{passed}/{total}",
                "correct_answer": ">= 75% AND Focus Lost = 0",
                "is_correct": status == "PASS",
                "level": "L4",
            }
        ],
    }


# =========================================================
# CORE EVALUATION (ALL ROUNDS)
# =========================================================

def evaluate_round_core(form_id: str, json_path: str) -> Dict[str, Any]:
    """
    Core evaluation logic for Streamlit & CLI
    """

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    candidate = data.get("candidate", {})
    uid = candidate.get("uid", "UNKNOWN_UID")
    candidate_name = candidate.get("name", "")
    email = candidate.get("email", "")

    # -------- L4 SHORT-CIRCUIT --------
    if form_id == "L4":
        return evaluate_l4_round(uid)

    # -------- L1 / L2 / L3 / L5 --------
    question_index = build_question_index(data)
    user_answers_by_qid = fetch_latest_answers(form_id)

    if not user_answers_by_qid:
        return {
            "uid": uid,
            "candidate_name": candidate_name,
            "email": email,
            "round_name": "UNKNOWN",
            "total_questions": 0,
            "correct_count": 0,
            "score_percent": 0.0,
            "status": "NO_RESPONSES",
            "spreadsheet_id": None,
            "details": [],
        }

    forms = get_forms_service()
    form_def = forms.forms().get(formId=form_id).execute()
    items = form_def.get("items", [])

    total_questions = 0
    correct_count = 0
    level_counts: Dict[str, int] = {}
    details: List[Dict[str, Any]] = []

    for item in items:
        q_item = item.get("questionItem")
        if not q_item:
            continue

        title = clean(item.get("title", ""))
        qid = q_item.get("question", {}).get("questionId")
        user_answer = clean(user_answers_by_qid.get(qid))

        if not title or not qid or not user_answer:
            continue

        total_questions += 1

        correct_answer, level = question_index.get(title, (None, "UNKNOWN"))
        level_counts[level] = level_counts.get(level, 0) + 1

        is_correct = correct_answer is not None and user_answer == clean(correct_answer)
        if is_correct:
            correct_count += 1

        details.append(
            {
                "title": title,
                "user_answer": user_answer,
                "correct_answer": correct_answer,
                "is_correct": is_correct,
                "level": level,
            }
        )

    if total_questions == 0:
        return {
            "uid": uid,
            "candidate_name": candidate_name,
            "email": email,
            "round_name": "UNKNOWN",
            "total_questions": 0,
            "correct_count": 0,
            "score_percent": 0.0,
            "status": "NO_EVALUATABLE_QUESTIONS",
            "spreadsheet_id": None,
            "details": [],
        }

    score_percent = round((correct_count / total_questions) * 100, 2)
    status = "PASS" if score_percent >= 75 else "FAIL"
    round_name = max(level_counts, key=level_counts.get) if level_counts else "UNKNOWN"

    spreadsheet_id = save_round_result(
        uid=uid,
        candidate_name=candidate_name,
        email=email,
        round_name=round_name,
        total_questions=total_questions,
        correct_answers=correct_count,
        score_percent=score_percent,
        status=status,
    )

    return {
        "uid": uid,
        "candidate_name": candidate_name,
        "email": email,
        "round_name": round_name,
        "total_questions": total_questions,
        "correct_count": correct_count,
        "score_percent": score_percent,
        "status": status,
        "spreadsheet_id": spreadsheet_id,
        "details": details,
    }


# =========================================================
# CLI SUPPORT
# =========================================================

def evaluate_round(form_id: str, json_path: str):
    result = evaluate_round_core(form_id, json_path)
    print(json.dumps(result, indent=2))


def evaluate_l4_round(result_path: str, candidate_data: dict):
    """
    Evaluate L4 coding round from persisted JSON result
    (Backward compatible & safe)
    """

    if not os.path.exists(result_path):
        return {"status": "NO_SUBMISSION"}

    with open(result_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    passed = int(data.get("passed", 0))
    total = int(data.get("total", 0))

    # ✅ SAFETY: compute score if missing
    if "score_percent" in data:
        score_percent = float(data["score_percent"])
    else:
        score_percent = round((passed / total) * 100, 2) if total else 0.0

    focus_lost = int(data.get("focus_lost", data.get("focus_violations", 0)))

    status = data.get("status", "FAIL")

    # 🔒 Enforce proctoring rule again (double safety)
    if focus_lost > 0:
        status = "FAIL"

    spreadsheet_id = save_round_result(
        uid=candidate_data["uid"],
        candidate_name=candidate_data["name"],
        email=candidate_data["email"],
        round_name="L4",
        total_questions=total,
        correct_answers=passed,
        score_percent=score_percent,
        status=status,
    )

    return {
        "passed": passed,
        "total": total,
        "score_percent": score_percent,
        "focus_lost": focus_lost,
        "status": status,
        "spreadsheet_id": spreadsheet_id,
    }


if __name__ == "__main__":
    form_id = input("Enter Form ID or 'L4': ").strip()
    json_path = input("Enter candidate JSON path: ").strip()
    evaluate_round(form_id, json_path)
